-- MySQL Script generated by MySQL Workbench
-- Sun Apr 14 13:55:12 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema assessmenttooldb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema assessmenttooldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `assessmenttooldb` DEFAULT CHARACTER SET utf8mb4 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `assessmenttooldb`.`organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assessmenttooldb`.`organization` (
  `nif` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`nif`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `assessmenttooldb`.`ibm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assessmenttooldb`.`ibm` (
  `ibm_id` BIGINT(20) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `survey_survey_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ibm_id`),
  INDEX `fk_ibm_survey1_idx` (`survey_survey_id` ASC) VISIBLE,
  CONSTRAINT `fk_ibm_survey1`
    FOREIGN KEY (`survey_survey_id`)
    REFERENCES `assessmenttooldb`.`survey` (`survey_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `assessmenttooldb`.`poete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assessmenttooldb`.`poete` (
  `poete_id` BIGINT(20) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `ibm_ibm_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`poete_id`),
  INDEX `fk_poete_ibm1_idx` (`ibm_ibm_id` ASC) VISIBLE,
  CONSTRAINT `fk_poete_ibm1`
    FOREIGN KEY (`ibm_ibm_id`)
    REFERENCES `assessmenttooldb`.`ibm` (`ibm_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `assessmenttooldb`.`survey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assessmenttooldb`.`survey` (
  `survey_id` BIGINT(20) NOT NULL,
  `building_done` BIT(1) NOT NULL,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `initiating_done` BIT(1) NOT NULL,
  `locked` BIT(1) NOT NULL,
  `maintaining_done` BIT(1) NOT NULL,
  `type` VARCHAR(255) NULL DEFAULT NULL,
  `organization_nif` VARCHAR(255) NULL DEFAULT NULL,
  `poete_poete_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`survey_id`),
  INDEX `FKrrtxf6g9t0agdhauw90o5rbnl` (`organization_nif` ASC) VISIBLE,
  INDEX `fk_survey_poete1_idx` (`poete_poete_id` ASC) VISIBLE,
  CONSTRAINT `FKrrtxf6g9t0agdhauw90o5rbnl`
    FOREIGN KEY (`organization_nif`)
    REFERENCES `assessmenttooldb`.`organization` (`nif`),
  CONSTRAINT `fk_survey_poete1`
    FOREIGN KEY (`poete_poete_id`)
    REFERENCES `assessmenttooldb`.`poete` (`poete_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `assessmenttooldb`.`question_text`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assessmenttooldb`.`question_text` (
  `question_text_id` VARCHAR(255) NOT NULL,
  `date_created` DATE NULL DEFAULT NULL,
  `question_text` VARCHAR(255) NULL DEFAULT NULL,
  `question_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`question_text_id`),
  INDEX `FKj9fj8rxij04sr1ph21nojxroe` (`question_id` ASC) VISIBLE,
  CONSTRAINT `FKj9fj8rxij04sr1ph21nojxroe`
    FOREIGN KEY (`question_id`)
    REFERENCES `assessmenttooldb`.`survey_question` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `assessmenttooldb`.`survey_question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assessmenttooldb`.`survey_question` (
  `id` BIGINT(20) NOT NULL,
  `answer` INT(11) NOT NULL,
  `is_compacted` BIT(1) NOT NULL,
  `question_id` VARCHAR(255) NULL DEFAULT NULL,
  `question_text_question_text_id` VARCHAR(255) NULL DEFAULT NULL,
  `survey_survey_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKs9vhypeq9akwkdwu3rt6bq6pv` (`question_text_question_text_id` ASC) VISIBLE,
  INDEX `FKed4kqchii5gjagy8p3ogxlxl7` (`survey_survey_id` ASC) VISIBLE,
  CONSTRAINT `FKed4kqchii5gjagy8p3ogxlxl7`
    FOREIGN KEY (`survey_survey_id`)
    REFERENCES `assessmenttooldb`.`survey` (`survey_id`),
  CONSTRAINT `FKs9vhypeq9akwkdwu3rt6bq6pv`
    FOREIGN KEY (`question_text_question_text_id`)
    REFERENCES `assessmenttooldb`.`question_text` (`question_text_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`risk_analysis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`risk_analysis` (
  `analysis_id` INT NULL,
  `analysis_description` TEXT NULL,
  `analysis_id` INT NULL,
  PRIMARY KEY (`analysis_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`survey_question_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`survey_question_type` (
  `survey_question_id` BIGINT(20) NOT NULL,
  `question_type_name` VARCHAR(50) NULL,
  `risk_analysis_analysis_id` INT NOT NULL,
  INDEX `fk_survey_question_type_survey_question_idx` (`survey_question_id` ASC) VISIBLE,
  INDEX `fk_survey_question_type_risk_analysis1_idx` (`risk_analysis_analysis_id` ASC) VISIBLE,
  CONSTRAINT `fk_survey_question_type_survey_question`
    FOREIGN KEY (`survey_question_id`)
    REFERENCES `assessmenttooldb`.`survey_question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_survey_question_type_risk_analysis1`
    FOREIGN KEY (`risk_analysis_analysis_id`)
    REFERENCES `mydb`.`risk_analysis` (`analysis_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`survey_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`survey_config` (
  `survey_question_id` INT NULL,
  `survey_survey_id` INT NULL,
  `question_type` VARCHAR(50) NULL,
  `question_id` INT NULL,
  INDEX `fk_survey_config_survey_question1_idx` (`survey_question_id` ASC) VISIBLE,
  PRIMARY KEY (`survey_question_id`),
  CONSTRAINT `fk_survey_config_survey_question1`
    FOREIGN KEY (`survey_question_id`)
    REFERENCES `assessmenttooldb`.`survey_question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`default`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`default` (
  `poete_poete_id` BIGINT(20) NOT NULL,
  `survey_survey_id` BIGINT(20) NOT NULL,
  INDEX `fk_default_poete1_idx` (`poete_poete_id` ASC) VISIBLE,
  INDEX `fk_default_survey1_idx` (`survey_survey_id` ASC) VISIBLE,
  CONSTRAINT `fk_default_poete1`
    FOREIGN KEY (`poete_poete_id`)
    REFERENCES `assessmenttooldb`.`poete` (`poete_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_default_survey1`
    FOREIGN KEY (`survey_survey_id`)
    REFERENCES `assessmenttooldb`.`survey` (`survey_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `assessmenttooldb` ;

-- -----------------------------------------------------
-- Table `assessmenttooldb`.`default_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assessmenttooldb`.`default_comment` (
  `id_string` VARCHAR(255) NOT NULL,
  `comment_text` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_string`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `assessmenttooldb`.`ibm_question_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assessmenttooldb`.`ibm_question_list` (
  `ibm_ibm_id` BIGINT(20) NOT NULL,
  `survey_survey_id` BIGINT(20) NOT NULL,
  INDEX `FKammdtg1u395dsyrys7xo95fec` (`ibm_ibm_id` ASC) VISIBLE,
  INDEX `fk_ibm_question_list_survey1_idx` (`survey_survey_id` ASC) VISIBLE,
  CONSTRAINT `FKammdtg1u395dsyrys7xo95fec`
    FOREIGN KEY (`ibm_ibm_id`)
    REFERENCES `assessmenttooldb`.`ibm` (`ibm_id`),
  CONSTRAINT `fk_ibm_question_list_survey1`
    FOREIGN KEY (`survey_survey_id`)
    REFERENCES `assessmenttooldb`.`survey` (`survey_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `assessmenttooldb`.`ibm_seq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assessmenttooldb`.`ibm_seq` (
  `next_val` BIGINT(20) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `assessmenttooldb`.`organization_survey_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assessmenttooldb`.`organization_survey_list` (
  `organization_nif` VARCHAR(255) NOT NULL,
  `survey_list_survey_id` BIGINT(20) NOT NULL,
  UNIQUE INDEX `UK_sgm11o1eqt5pkerlw4bdwkf97` (`survey_list_survey_id` ASC) VISIBLE,
  INDEX `FKj09vc4w5kv0m4ch3121em92u5` (`organization_nif` ASC) VISIBLE,
  CONSTRAINT `FK8ecumi3tjj65t92ttvwnt8gb9`
    FOREIGN KEY (`survey_list_survey_id`)
    REFERENCES `assessmenttooldb`.`survey` (`survey_id`),
  CONSTRAINT `FKj09vc4w5kv0m4ch3121em92u5`
    FOREIGN KEY (`organization_nif`)
    REFERENCES `assessmenttooldb`.`organization` (`nif`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `assessmenttooldb`.`poete_question_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assessmenttooldb`.`poete_question_list` (
  `poete_poete_id` BIGINT(20) NOT NULL,
  `survey_survey_id` BIGINT(20) NOT NULL,
  INDEX `FKtgb2pf2t6q2sb64vambqvh77q` (`poete_poete_id` ASC) VISIBLE,
  INDEX `fk_poete_question_list_survey1_idx` (`survey_survey_id` ASC) VISIBLE,
  CONSTRAINT `FKtgb2pf2t6q2sb64vambqvh77q`
    FOREIGN KEY (`poete_poete_id`)
    REFERENCES `assessmenttooldb`.`poete` (`poete_id`),
  CONSTRAINT `fk_poete_question_list_survey1`
    FOREIGN KEY (`survey_survey_id`)
    REFERENCES `assessmenttooldb`.`survey` (`survey_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `assessmenttooldb`.`poete_seq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assessmenttooldb`.`poete_seq` (
  `next_val` BIGINT(20) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `assessmenttooldb`.`score_explanation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assessmenttooldb`.`score_explanation` (
  `score_exp_id` VARCHAR(255) NOT NULL,
  `date_created` DATE NULL DEFAULT NULL,
  `question_id` VARCHAR(255) NULL DEFAULT NULL,
  `score_exp` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`score_exp_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `assessmenttooldb`.`question_score_explanation_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assessmenttooldb`.`question_score_explanation_list` (
  `question_id` BIGINT(20) NOT NULL,
  `score_explanation_list_score_exp_id` VARCHAR(255) NOT NULL,
  INDEX `FK7dbq9q0dhjjwtscx04d0ii9ll` (`score_explanation_list_score_exp_id` ASC) VISIBLE,
  INDEX `FKaksqu4jai89g8mssblhp7r5u8` (`question_id` ASC) VISIBLE,
  CONSTRAINT `FK7dbq9q0dhjjwtscx04d0ii9ll`
    FOREIGN KEY (`score_explanation_list_score_exp_id`)
    REFERENCES `assessmenttooldb`.`score_explanation` (`score_exp_id`),
  CONSTRAINT `FKaksqu4jai89g8mssblhp7r5u8`
    FOREIGN KEY (`question_id`)
    REFERENCES `assessmenttooldb`.`survey_question` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `assessmenttooldb`.`question_seq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assessmenttooldb`.`question_seq` (
  `next_val` BIGINT(20) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `assessmenttooldb`.`survey_seq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assessmenttooldb`.`survey_seq` (
  `next_val` BIGINT(20) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
